CREATE TABLE submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  email TEXT NOT NULL,
  spreadsheetId TEXT NOT NULL,
  requestedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  emailSent BOOLEAN DEFAULT TRUE
);